// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gocflenvoyagkxdbwxjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvY2ZsZW52b3lhZ2t4ZGJ3eGpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1NDM0NjksImV4cCI6MjA1MDExOTQ2OX0.MfpxWarpxT5dWzW5NBxgaP82mdsdaJ3uFikTuHCKDPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);